---
title: "This is my title"
author: "Reinout"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
```

### Introduction

hoi

### Visualisation

```{r}
aisc2024 <- read_csv("compmus2025.csv")

aisc2024 |>                   # Start with the data
  ggplot(                     # Set up the plot.
    aes(
      x = tempo,
      y = engagingness,
      size = danceability,
      colour = arousal,
      label = filename
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    x = 90,
    y = 1.0174429416656494,
    label = "reinout-w-1",
    size = 2,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical centre of label with the point.
    angle = 30,                # Rotate the text label
    color = "black"                # Rotate the text label
  ) +
  geom_text(                  # Add text labels from above.
    x = 103,
    y = 0.9157294034957886,
    label = "reinout-w-2",
    size = 2,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical centre of label with the point.
    angle = 30,                # Rotate the text label
    color = "black"
  ) +
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(70, 160),
    breaks = c(70, 115, 160), # Specify grid lines
    minor_breaks = NULL       # Remove 'minor' grid lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(0, 1.2),
    breaks = c(0, 0.6, 1.2),
    minor_breaks = NULL
  ) +
  scale_colour_viridis_c() +  # Use the popular viridis colour palette.
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud..
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Tempo",
    y = "Engagingness",
    colour = "Arousal"
  )
ggplotly()
```

***

extra info about the plot

### Conclusion

bye